# Generated by Django 3.0.2 on 2020-02-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteam', models.TextField()),
                ('price', models.CharField(max_length=200)),
            ],
        ),
    ]
